name: CI

on:
  push:
  pull_request:

env:
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2026-04-20
          components: rustfmt, clippy
      - run: cargo test --workspace

  miri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2026-04-20
          components: miri, rust-src
      - run: yes | cargo miri setup
      - run: cargo miri test -p compact-option
